### ISSUE TITLE
Doesn't work with WireGuard

### ISSUE THREAD

**Issue by FaBMak** [rs-develop/gnome-shell-extension-protectmevpn#1]
I had to tweak extension.js

    //Checks if a vpn is active
    _isVPNActive: function() {
        // for open vpn
        var [res, vpn] = GLib.spawn_sync(null, ["/bin/bash", "-c", "nmcli con show --active | grep vpn"], null, GLib.SpawnFlags.SEARCH_PATH, null);
        if (vpn.length > 0)
            return vpn
        else {
            var [res, tun] = GLib.spawn_sync(null, ["/bin/bash", "-c", "nmcli con show --active | grep tun"], null, GLib.SpawnFlags.SEARCH_PATH, null);
            if (tun.length > 0)
            	return tun
            else {
            	var [res, wg] = GLib.spawn_sync(null, ["/bin/bash", "-c", "nmcli con show --active | grep wg"], null, GLib.SpawnFlags.SEARCH_PATH, null);
            	return wg
            }
        }
    },//end _isVPNActive

**Comment by rs-develop** [comment]
Thank you for the response. I will add a patch soon.

**Comment by rs-develop** [comment]
Solved
